pipeline:
  name: LambdaZipall
  identifier: LambdaZipall
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github
        repoName: newLambdatestingcode
        build: <+input>
  stages:
    - stage:
        name: Clone
        identifier: Clone
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: CompressFile
                  identifier: CompressFile
                  spec:
                    shell: Sh
                    command: zip -r lambda.zip lambda/
              - step:
                  type: Run
                  name: UploadArtifactToS3
                  identifier: UploadArtifactToS3
                  spec:
                    shell: Sh
                    command: "aws configure set aws_access_key_id <+pipeline.variables.Accesskey>\r\naws configure set aws_secret_access_key <+pipeline.variables.Secretkey>\r\naws s3 cp lambda.zip s3://lambdacodezip123/"
              - step:
                  type: Run
                  name: UpdateLambdaFunction
                  identifier: UpdateLambdaFunction
                  spec:
                    shell: Sh
                    command: |-
                      aws configure set aws_access_key_id <+pipeline.variables.Accesskey>
                      aws configure set aws_secret_access_key <+pipeline.variables.Secretkey>
                      aws lambda update-function-code --function-name lambdafunctioncodetest1 --s3-bucket lambdacodezip123 --s3-key lambda.zip --region us-east-2
                      aws lambda update-function-code --function-name lambdafunctioncodetest2 --s3-bucket lambdacodezip123 --s3-key lambda.zip --region us-east-2
  variables:
    - name: Accesskey
      type: Secret
      description: ""
      required: false
      value: Accesskey
    - name: Secretkey
      type: Secret
      description: ""
      required: false
      value: Secretkey
